AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  registration:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.honeybuns.serverless.api.handler.RegistrationHandler
      CodeUri: ./build/distributions/honeybunsapi-serverless-1.0.0-SNAPSHOT.zip
      Runtime: java8
      Timeout: 300
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        PostEvent:
          Type: Api
          Properties:
            Path: /register
            Method: post
